### ISSUE TITLE
unable to import 'addToConfusionMatrix'

### ISSUE THREAD

**Issue by sbharadwajj** [freedrone/cityscapesScripts#1]
Hi,
I'm unable to import this module even though i have enabled cython on my python venv.
This is the error i'm getting:
```
No module named 'addToConfusionMatrix'
Evaluating 500 pairs of images...
Traceback (most recent call last):
  File "evalPixelLevelSemanticLabeling.py", line 765, in <module>
    main()
  File "evalPixelLevelSemanticLabeling.py", line 758, in main
    evaluateImgLists(predictionImgList, groundTruthImgList, args)
  File "evalPixelLevelSemanticLabeling.py", line 511, in evaluateImgLists
    args)
  File "evalPixelLevelSemanticLabeling.py", line 675, in evaluatePair
    confMatrix[groundTruthImgPixel][predictionImgPixel] += 1
IndexError: index 26000 is out of bounds for axis 0 with size 35
```

modification:
I've even appended the path to avoid path problems.
```
if CSUPPORT:
    try:
        sys.path.insert(0,'../cityscapes/cityscapes-scripts/cityscapesscripts/evaluation')
        import addToConfusionMatrix
        sys.path.remove('/cityscapes/cityscapes-scripts/cityscapesscripts/evaluation')
```
Is there anyway i can fix this?

**Comment by sbharadwajj** [comment]
I had to run setup.py like this
`setup.py build_ext --inplace`
